def get_stp(program: int, ion: int, target: int, energy: float) -> float: ...
def get_stp_table(program: int, ion: int, target: int, energies: list[float]) -> list[float]: ...
def get_default_table(program: int, ion: int, target: int) -> tuple[list[float], list[float]]: ...
def get_csda_table(program: int, ion: int, target: int, energies: list[float]) -> list[float]: ...
