#!/usr/bin/env python3
"""
Convert libdedx stopping power .dat files to embeddable C headers.

All energy axes are normalised to MeV/nucl (kinetic energy per nucleon) in the
generated headers so that the lookup code needs no per-dataset unit logic.

ASTAR and ICRU_ASTAR are already tabulated on a MeV/nucl grid in the checked-in
`*Eng.dat` files and must not be rescaled here. Only datasets whose raw energy
files are still in total kinetic energy are converted on the way out.

Array layout
------------
All datasets use a uniform 3-D layout:

    dedx_<prog>_stp[n_ions][n_targets][n_energies]

Single-ion datasets (PSTAR, ASTAR, …) have n_ions=1.

Companion arrays:
    dedx_<prog>_energy[]      energy grid in MeV/nucl
    dedx_<prog>_ion_ids[]     projectile Z values
    dedx_<prog>_target_ids[]  NIST/ICRU material IDs (= Z for elements)

Usage:
    python3 tools/dat2c.py pstar
    python3 tools/dat2c.py all
"""

import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Dataset catalogue
# ---------------------------------------------------------------------------

# (dat_file, energy_file, energy_scale)
# energy_scale: multiply raw file energy values by this to convert to MeV/nucl.
# Most datasets are already in MeV/nucl natively. The current checked-in ASTAR and
# ICRU_ASTAR energy grids are also already in MeV/nucl, despite the original NIST
# UI using total alpha energy in MeV.
# Datasets still stored in total kinetic energy are scaled here:
#   alpha  A=4  → scale 1/4
#   carbon A=12 → scale 1/12
# Electrons and positrons are listed with scale 1.0 (MeV ≡ MeV/nucl for leptons).
DATASETS = {
    "astar":       ("ASTAR.dat",      "astarEng.dat",      1.0),
    "pstar":       ("PSTAR.dat",      "pstarEng.dat",      1.0),
    "estar":       ("ESTAR.dat",      "estarEng.dat",      1.0),
    "mstar":       ("MSTAR.dat",      "mstarEng.dat",      1.0),
    "icru73":      ("ICRU73.dat",     "icru73Eng.dat",     1.0),
    "icru73new":   ("ICRU73_NEW.dat", "icru73_newEng.dat", 1.0),
    "icru_pstar":  ("ICRU_PSTAR.dat", "icru_pstarEng.dat", 1.0),
    "icru_astar":  ("ICRU_ASTAR.dat", "icru_astarEng.dat", 1.0),
    # ICRU Report 90 datasets (generated by pdf2dat.py from icru_90_raw.txt)
    "icru90_e":    ("ICRU90_e.dat",   "icru90_eEng.dat",   1.0),
    "icru90_pos":  ("ICRU90_pos.dat", "icru90_posEng.dat", 1.0),
    "icru90_p":    ("ICRU90_p.dat",   "icru90_pEng.dat",   1.0),
    "icru90_a":    ("ICRU90_a.dat",   "icru90_aEng.dat",   1.0 / 4),
    "icru90_C":    ("ICRU90_C.dat",   "icru90_CEng.dat",   1.0 / 12),
}

# Energy-grid only (no stopping data; Bethe is calculated analytically)
ENERGY_ONLY = {
    "bethe": ("betheEng.dat", 1.0),
}

# ---------------------------------------------------------------------------
# File readers
# ---------------------------------------------------------------------------

def read_energy(path):
    """Read *Eng.dat: first line = count, remaining lines = values."""
    with open(path) as fh:
        lines = [ln.strip() for ln in fh if ln.strip()]
    n = int(lines[0])
    values = [float(ln) for ln in lines[1:]]
    if len(values) != n:
        raise ValueError(f"{path}: header says {n} values, found {len(values)}")
    return values


def read_dat(path):
    """
    Read PROG.dat.  Header lines have the form  #<target>:<ion>:<n_points>
    followed by n_points floating-point data lines.
    Returns a list of (target, ion, [float, ...]).
    """
    entries = []
    target = ion = n_pts = 0
    buf = []
    with open(path) as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            if line[0] == "#":
                parts = line[1:].split(":")
                target, ion, n_pts = int(parts[0]), int(parts[1]), int(parts[2])
                buf = []
            else:
                buf.append(float(line))
                if len(buf) == n_pts:
                    entries.append((target, ion, list(buf)))
    return entries

# ---------------------------------------------------------------------------
# C array emitters
# ---------------------------------------------------------------------------

# Column width constants chosen so lines stay inside the 120-char project limit.
#   float literal "1.234567e+08f" = 13 chars, ", " = 2 chars
#   7 floats × 13 + 6 × 2 +  4-sp indent  = 91 + 12 + 4  = 107  ✓ (1-D / 2-D outer)
#   6 floats × 13 + 5 × 2 +  8-sp indent  = 78 + 10 + 8  =  96  ✓ (2-D inner / 3-D middle)
#   6 floats × 13 + 5 × 2 + 12-sp indent  = 78 + 10 + 12 = 100  ✓ (3-D inner)
_COLS_FLOAT_1D  = 7
_COLS_FLOAT_3D  = 6
_COLS_INT       = 15

_I1 = "    "        # 4 spaces  — outer level
_I2 = "        "    # 8 spaces  — middle level
_I3 = "            "  # 12 spaces — inner level


def _ff(v):
    """Format a single float literal."""
    return f"{v:.6e}f"


def _int_rows(values, cols):
    """Yield formatted rows for an integer initialiser list."""
    chunk = []
    for v in values:
        chunk.append(f"{v:4d}")
        if len(chunk) == cols:
            yield _I1 + ", ".join(chunk) + ","
            chunk = []
    if chunk:
        yield _I1 + ", ".join(chunk) + ","


def _float_rows(values, indent, cols):
    """Yield formatted rows for a float initialiser list."""
    chunk = []
    for v in values:
        chunk.append(_ff(v))
        if len(chunk) == cols:
            yield indent + ", ".join(chunk) + ","
            chunk = []
    if chunk:
        yield indent + ", ".join(chunk) + ","


def emit_int_array(name, values):
    lines = [f"static const int {name}[{len(values)}] = {{"]
    lines.extend(_int_rows(values, _COLS_INT))
    lines.append("};")
    return lines


def emit_float_1d(name, values):
    lines = [f"static const float {name}[{len(values)}] = {{"]
    lines.extend(_float_rows(values, _I1, _COLS_FLOAT_1D))
    lines.append("};")
    return lines



def emit_float_3d(name, arr, outer_labels, inner_labels):
    """
    arr[i][j]       : list of float   layout: [n_outer][n_inner][n_energy]
    outer_labels[i] : comment on outer brace (e.g. "ion 3")
    inner_labels[j] : comment on inner brace (e.g. "target 1")
    """
    n0 = len(arr)
    n1 = len(arr[0])
    n2 = len(arr[0][0]) if arr[0] else 0
    lines = [f"static const float {name}[{n0}][{n1}][{n2}] = {{"]
    for i, plane in enumerate(arr):
        osep = "," if i < n0 - 1 else ""
        lines.append(f"{_I1}{{  /* {outer_labels[i]} */")
        for j, row in enumerate(plane):
            isep = "," if j < n1 - 1 else ""
            lines.append(f"{_I2}{{  /* {inner_labels[j]} */")
            lines.extend(_float_rows(row, _I3, _COLS_FLOAT_3D))
            lines.append(f"{_I2}}}{isep}")
        lines.append(f"{_I1}}}{osep}")
    lines.append("};")
    return lines

# ---------------------------------------------------------------------------
# Header generator
# ---------------------------------------------------------------------------

def _header_lines(name, source_files, note=""):
    """Opening boilerplate (guard + clang-format off)."""
    sources = ", ".join(source_files)
    guard = f"DEDX_DATA_{name.upper()}_H"
    lines = [
        f"/* Auto-generated from {sources} -- do not edit.",
        f" * Regenerate: python3 tools/dat2c.py {name}",
    ]
    if note:
        lines.append(f" * {note}")
    lines += [
        " */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* clang-format off */",
        "",
    ]
    return lines


def _footer_lines(name):
    """Closing boilerplate (clang-format on + end guard)."""
    guard = f"DEDX_DATA_{name.upper()}_H"
    return [
        "",
        "/* clang-format on */",
        "",
        f"#endif /* {guard} */",
        "",
    ]


def generate(name, dat_path, eng_path, energy_scale):
    energy  = [v * energy_scale for v in read_energy(eng_path)]
    entries = read_dat(dat_path)

    targets   = sorted({e[0] for e in entries})
    ions      = sorted({e[1] for e in entries})
    pfx       = f"dedx_{name}"

    scale_note = "" if energy_scale == 1.0 else f" (scaled by {energy_scale} from raw file)"
    L = _header_lines(name, [Path(dat_path).name, Path(eng_path).name],
                      f"Energy values are in MeV/nucl (kinetic energy per nucleon).{scale_note}")

    # Uniform 3D layout: [n_ions][n_targets][n_energies]
    # Single-ion datasets have n_ions=1 and an _ion_ids array with one entry.
    L.extend(emit_float_1d(f"{pfx}_energy", energy))
    L.append("")

    L.extend(emit_int_array(f"{pfx}_ion_ids", ions))
    L.append("")

    L.extend(emit_int_array(f"{pfx}_target_ids", targets))
    L.append("")

    ion_idx    = {v: i for i, v in enumerate(ions)}
    target_idx = {v: i for i, v in enumerate(targets)}
    arr = [[[0.0] * len(energy) for _ in targets] for _ in ions]
    for t, io, vals in entries:
        arr[ion_idx[io]][target_idx[t]] = vals

    L.extend(emit_float_3d(
        f"{pfx}_stp", arr,
        outer_labels=[f"ion {io}" for io in ions],
        inner_labels=[f"target {t}" for t in targets],
    ))

    L.extend(_footer_lines(name))
    return "\n".join(L)


def generate_energy_only(name, eng_path, energy_scale):
    """Bethe: energy grid only, no stopping table."""
    energy = [v * energy_scale for v in read_energy(eng_path)]
    pfx    = f"dedx_{name}"

    L = _header_lines(name, [Path(eng_path).name],
                      "Energy values are in MeV/nucl (kinetic energy per nucleon).")
    L.extend(emit_float_1d(f"{pfx}_energy", energy))
    L.extend(_footer_lines(name))
    return "\n".join(L)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    raw_dir = repo_root / "data" / "raw"
    embedded_dir = repo_root / "src" / "data" / "embedded"

    requested = sys.argv[1:] if len(sys.argv) > 1 else ["all"]
    if requested == ["all"]:
        requested = list(DATASETS) + list(ENERGY_ONLY)

    for name in requested:
        if name in DATASETS:
            dat, eng, scale = DATASETS[name]
            outfile = embedded_dir / f"dedx_{name}.h"
            print(f"Generating {outfile} ...")
            with open(outfile, "w") as fh:
                fh.write(generate(name, raw_dir / dat, raw_dir / eng, scale))
        elif name in ENERGY_ONLY:
            eng, scale = ENERGY_ONLY[name]
            outfile = embedded_dir / f"dedx_{name}.h"
            print(f"Generating {outfile} (energy only) ...")
            with open(outfile, "w") as fh:
                fh.write(generate_energy_only(name, raw_dir / eng, scale))
        else:
            print(f"Unknown dataset: {name!r}", file=sys.stderr)
            avail = ", ".join(list(DATASETS) + list(ENERGY_ONLY))
            print(f"Available: {avail}", file=sys.stderr)
            sys.exit(1)

    print("Done.")


if __name__ == "__main__":
    main()
