name: Docs

on: [push]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build and Deploy
        # Deploys to GitHub Pages only on main or release tags (v*)
        if: "github.ref == 'refs/heads/main' || (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v'))"
        uses: sphinx-notes/pages@3.6
        with:
          documentation_path: docs/source
          requirements_path: docs/source/requirements.txt
