name: Automated actions

on: [push]

jobs:
  compile_code:
      runs-on:  ${{ matrix.platform }}
      strategy:
       matrix:
         platform: [ubuntu-latest, windows-latest]
      steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Compile with CMake
        run: | 
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../ -DCMAKE_INSTALL_PREFIX=$HOME/usr
          cmake --build . --target install -- -j2

  build_docs:
    runs-on: ubuntu-latest
    needs: [compile_code]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@1.0
      with:
        documentation_path: docs/source
    - name: Push changes to gh-pages branch
      # this action is being triggered:
      #  - on master branch
      #  - on release tags (named v*)
      if: "github.ref == 'refs/heads/master' || (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v'))"
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages